#!/usr/bin/env python3
"""Independent verifier for the native macOS Metal readiness diagnostic.

The verifier detects malformed or internally inconsistent self-asserted
evidence. It does not authenticate the runner, host, device, or capture.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import signal
import struct
import subprocess
import sys
import threading
import time
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple


SCHEMA = "glacier.native-metal-readiness/macos-v1"
DEVICE_INFO_ABI = 0x474D444900000001
DISPATCH_RECEIPT_ABI = 0x474D445000000001
DIAGNOSTIC_REPORT_ABI = 0x474D445800000001
WORKLOAD_EVIDENCE_ABI = 0x474D455600000001
DEVICE_IDENTITY_DOMAIN = b"glacier-metal-device-identity-v1\x00"
PLACEMENT_IDENTITY_DOMAIN = b"glacier-metal-placement-identity-v1\x00"
MACHINE_IDENTITY_DOMAIN = b"glacier-metal-readiness-machine-v1\x00"
DISPATCH_RECEIPT_DOMAIN = b"glacier-metal-dispatch-receipt-v1\x00"
DIAGNOSTIC_REPORT_DOMAIN = b"glacier-metal-readiness-diagnostic-v1\x00"
CORRECTNESS_DOMAIN = b"glacier-metal-readiness-correctness-v1\x00"
OWNERSHIP_DOMAIN = b"glacier-metal-readiness-ownership-v1\x00"
COMPLETED_COMMAND_BUFFER_STATUS = 4
IN_FEATURES = 64
OUT_FEATURES = 37
GROUP_SIZE = 8
MAXIMUM_ABS_ERROR_BITS = 0x37A7C5AC
MAXIMUM_ABS_ERROR = struct.unpack(
    "<f", struct.pack("<I", MAXIMUM_ABS_ERROR_BITS)
)[0]
MAX_RUNNER_OUTPUT_BYTES = 1 << 20
MAX_JSON_INTEGER_DIGITS = 20
RUNNER_TIMEOUT_SECONDS = 60.0
RUNNER_TERMINATE_GRACE_SECONDS = 0.25
U64_MAX = (1 << 64) - 1
SHA256_RE = re.compile(r"[0-9a-f]{64}", re.ASCII)

# These roots are fixed by the macOS-v1 fixture and were generated by the
# canonical Zig implementation. Keeping literal values here makes the Python
# verifier independent of the producer's local self-hashes.
CANONICAL_WORKLOAD_PROFILE_SHA256 = (
    "a1691691219ec553d28d58ac39f33a65017d3260d940b438aace52c86eaf99c3"
)
CANONICAL_ARTIFACT_SHA256 = (
    "9ee185ded4aeeac487ca406ecae81d68935148cfde73df71cfd878fdaf66ec82"
)
CANONICAL_BUILD_SHA256 = (
    "bd0389d07ff127c70355a0bd7c8856e99082fb990a4f977ea31f513f57d53b26"
)
CANONICAL_BACKEND_SHA256 = (
    "14cf39adceb28668e532854cfbada5d8592254ea25fc8e9ba036b9ab104b6b4a"
)
CANONICAL_CHALLENGE_SHA256 = (
    "9c49f428550922edde0c5c3d41169c6c69c09ab6deb69f89fe9d1f00b02f05f0"
)
CANONICAL_ORACLE_OUTPUT_SHA256 = (
    "d7b9092893a9d7eef234474531202509f2884dedf8ba956166a93b2bd2fb909a"
)

DIRECT_METRICS = (1, 2, 32, 33, 35, 43)
UNSUPPORTED_METRICS = (
    "accelerator_utilization",
    "accelerator_committed_bytes",
    "accelerator_resident_bytes",
    "accelerator_queue_depth",
    "accelerator_temperature",
    "accelerator_frequency",
    "accelerator_power",
    "accelerator_energy",
)
UNSUPPORTED_METRIC_IDS = (34, 36, 37, 38, 39, 40, 41, 42)
DIRECT_METRIC_BITS = sum(1 << metric for metric in DIRECT_METRICS)
UNSUPPORTED_METRIC_BITS = sum(
    1 << metric for metric in UNSUPPORTED_METRIC_IDS
)

SHA_FIELDS = frozenset(
    (
        "output_sha256",
        "descriptor_sha256",
        "plan_descriptor_sha256",
        "report_descriptor_sha256",
        "diagnostic_descriptor_sha256",
        "workload_profile_sha256",
        "artifact_sha256",
        "build_sha256",
        "backend_sha256",
        "machine_sha256",
        "challenge_sha256",
        "plan_sha256",
        "report_plan_sha256",
        "diagnostic_plan_sha256",
        "plan_device_sha256",
        "receipt_device_sha256",
        "diagnostic_device_sha256",
        "plan_placement_sha256",
        "receipt_placement_sha256",
        "diagnostic_placement_sha256",
        "probe_bundle_sha256",
        "diagnostic_probe_bundle_sha256",
        "pre_run_bundle_sha256",
        "diagnostic_pre_run_bundle_sha256",
        "post_run_bundle_sha256",
        "diagnostic_post_run_bundle_sha256",
        "workload_receipt_sha256",
        "report_workload_receipt_sha256",
        "diagnostic_workload_receipt_sha256",
        "run_report_sha256",
        "diagnostic_run_report_sha256",
        "dispatch_receipt_sha256",
        "diagnostic_dispatch_receipt_sha256",
        "oracle_output_sha256",
        "correctness_sha256",
        "ownership_sha256",
        "report_sha256",
    )
)

U64_FIELDS = frozenset(
    (
        "device_info_abi",
        "device_registry_id",
        "dispatch_device_registry_id",
        "diagnostic_device_registry_id",
        "recommended_max_working_set_size",
        "device_location",
        "device_location_number",
        "device_max_threads_x",
        "device_max_threads_y",
        "device_max_threads_z",
        "device_low_power",
        "device_headless",
        "device_removable",
        "device_unified_memory",
        "logical_cpu_count",
        "queue_count",
        "direct_metric_bits",
        "unsupported_metric_bits",
        "missing_observation_count",
        "unsupported_observation_count",
        "unavailable_reason_count",
        "present_reason_count",
        "dispatch_ordinal",
        "host_submit_ticks",
        "host_complete_ticks",
        "current_allocated_before",
        "current_allocated_after",
        "gpu_start_time_bits",
        "gpu_end_time_bits",
        "gpu_duration_nanoseconds",
        "command_status",
        "live_weights_after",
        "workload_evidence_abi",
        "max_abs_error_bits",
        "live_weights_before",
        "workload_live_weights_after",
        "completed_dispatches_before",
        "completed_dispatches_after",
        "workload_invocations",
        "profile_count",
        "item_count",
    )
)

REPORT_FIELDS = frozenset(
    {
        "schema",
        "claim_class",
        "performance_claim",
        "decision",
        "workload_status",
        "correctness",
        "zero_orphans",
        "fallback",
        "unsupported_metrics",
    }
    | SHA_FIELDS
    | U64_FIELDS
)


class ReadinessError(RuntimeError):
    """A Metal readiness report is malformed or contradicts its claims."""


def _u64(value: Any, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ReadinessError(f"{field} must be an unsigned integer")
    if value < 0 or value > U64_MAX:
        raise ReadinessError(f"{field} is outside u64")
    return value


def _u32(value: Any, field: str) -> int:
    value = _u64(value, field)
    if value > 0xFFFFFFFF:
        raise ReadinessError(f"{field} is outside u32")
    return value


def _sha256_bytes(value: Any, field: str) -> bytes:
    if not isinstance(value, str) or SHA256_RE.fullmatch(value) is None:
        raise ReadinessError(f"{field} must be lowercase SHA-256")
    try:
        result = bytes.fromhex(value)
    except ValueError as exc:
        raise ReadinessError(f"{field} must be lowercase SHA-256") from exc
    if len(result) != 32 or result == bytes(32):
        raise ReadinessError(f"{field} must be nonzero")
    return result


def _hash_u64(hasher: Any, value: int) -> None:
    hasher.update(struct.pack("<Q", value))


def _double_from_bits(value: int) -> float:
    return struct.unpack("<d", struct.pack("<Q", value))[0]


def _float_from_bits(value: int) -> float:
    return struct.unpack("<f", struct.pack("<I", value))[0]


def device_identity_sha256(report: Mapping[str, Any]) -> str:
    hasher = hashlib.sha256()
    hasher.update(DEVICE_IDENTITY_DOMAIN)
    for field in (
        "device_info_abi",
        "device_registry_id",
        "recommended_max_working_set_size",
        "device_location",
        "device_location_number",
        "device_max_threads_x",
        "device_max_threads_y",
        "device_max_threads_z",
        "device_low_power",
        "device_headless",
        "device_removable",
        "device_unified_memory",
    ):
        _hash_u64(hasher, _u64(report.get(field), field))
    return hasher.hexdigest()


def placement_identity_sha256(report: Mapping[str, Any]) -> str:
    hasher = hashlib.sha256()
    hasher.update(PLACEMENT_IDENTITY_DOMAIN)
    for field in (
        "device_registry_id",
        "device_location",
        "device_location_number",
        "device_low_power",
        "device_headless",
        "device_removable",
        "device_unified_memory",
    ):
        _hash_u64(hasher, _u64(report.get(field), field))
    return hasher.hexdigest()


def machine_identity_sha256(report: Mapping[str, Any]) -> str:
    hasher = hashlib.sha256()
    hasher.update(MACHINE_IDENTITY_DOMAIN)
    _hash_u64(
        hasher,
        _u64(report.get("logical_cpu_count"), "logical_cpu_count"),
    )
    hasher.update(
        _sha256_bytes(report.get("plan_device_sha256"), "plan_device_sha256")
    )
    return hasher.hexdigest()


def dispatch_receipt_sha256(report: Mapping[str, Any]) -> str:
    hasher = hashlib.sha256()
    hasher.update(DISPATCH_RECEIPT_DOMAIN)
    _hash_u64(hasher, DISPATCH_RECEIPT_ABI)
    for field in (
        "dispatch_device_registry_id",
        "dispatch_ordinal",
        "host_submit_ticks",
        "host_complete_ticks",
        "current_allocated_before",
        "current_allocated_after",
        "recommended_max_working_set_size",
        "gpu_start_time_bits",
        "gpu_end_time_bits",
        "gpu_duration_nanoseconds",
        "command_status",
        "live_weights_after",
    ):
        _hash_u64(hasher, _u64(report.get(field), field))
    hasher.update(_sha256_bytes(report.get("output_sha256"), "output_sha256"))
    return hasher.hexdigest()


def correctness_sha256(report: Mapping[str, Any]) -> str:
    max_abs_error_bits = _u32(
        report.get("max_abs_error_bits"),
        "max_abs_error_bits",
    )
    maximum = _float_from_bits(max_abs_error_bits)
    passed = (
        math.isfinite(maximum)
        and maximum >= 0
        and maximum <= MAXIMUM_ABS_ERROR
    )
    hasher = hashlib.sha256()
    hasher.update(CORRECTNESS_DOMAIN)
    for value in (
        _u64(
            report.get("workload_evidence_abi"),
            "workload_evidence_abi",
        ),
        max_abs_error_bits,
        int(passed),
        IN_FEATURES,
        OUT_FEATURES,
        GROUP_SIZE,
    ):
        _hash_u64(hasher, value)
    hasher.update(
        _sha256_bytes(
            report.get("oracle_output_sha256"),
            "oracle_output_sha256",
        )
    )
    hasher.update(_sha256_bytes(report.get("output_sha256"), "output_sha256"))
    return hasher.hexdigest()


def ownership_sha256(report: Mapping[str, Any]) -> str:
    hasher = hashlib.sha256()
    hasher.update(OWNERSHIP_DOMAIN)
    for field in (
        "workload_evidence_abi",
        "live_weights_before",
        "workload_live_weights_after",
        "completed_dispatches_before",
        "completed_dispatches_after",
    ):
        _hash_u64(hasher, _u64(report.get(field), field))
    return hasher.hexdigest()


def diagnostic_report_sha256(report: Mapping[str, Any]) -> str:
    hasher = hashlib.sha256()
    hasher.update(DIAGNOSTIC_REPORT_DOMAIN)
    _hash_u64(hasher, DIAGNOSTIC_REPORT_ABI)
    _hash_u64(hasher, 1)
    _hash_u64(hasher, 0)
    for field in (
        "device_registry_id",
        "logical_cpu_count",
        "queue_count",
        "direct_metric_bits",
        "unsupported_metric_bits",
        "missing_observation_count",
        "unsupported_observation_count",
        "unavailable_reason_count",
        "present_reason_count",
    ):
        _hash_u64(hasher, _u64(report.get(field), field))
    for field in (
        "diagnostic_descriptor_sha256",
        "diagnostic_plan_sha256",
        "diagnostic_device_sha256",
        "diagnostic_placement_sha256",
        "diagnostic_probe_bundle_sha256",
        "diagnostic_pre_run_bundle_sha256",
        "diagnostic_post_run_bundle_sha256",
        "diagnostic_workload_receipt_sha256",
        "diagnostic_run_report_sha256",
        "diagnostic_dispatch_receipt_sha256",
    ):
        hasher.update(_sha256_bytes(report.get(field), field))
    return hasher.hexdigest()


def validate_report(report: Mapping[str, Any]) -> None:
    """Verify internal composition, not external capture authenticity."""
    actual_fields = frozenset(report.keys())
    if actual_fields != REPORT_FIELDS:
        missing = sorted(str(field) for field in REPORT_FIELDS - actual_fields)
        unknown = sorted(str(field) for field in actual_fields - REPORT_FIELDS)
        raise ReadinessError(
            "readiness field set changed "
            f"(missing={missing}, unknown={unknown})"
        )
    if report.get("schema") != SCHEMA:
        raise ReadinessError("unexpected readiness schema")
    if report.get("claim_class") != "diagnostic":
        raise ReadinessError("readiness output must remain diagnostic")
    if report.get("performance_claim") is not False:
        raise ReadinessError("readiness output cannot claim performance")
    if report.get("decision") != "publishable":
        raise ReadinessError("native observation runner did not publish")
    if report.get("workload_status") != "succeeded":
        raise ReadinessError("Metal workload did not succeed")
    if report.get("correctness") != "passed":
        raise ReadinessError("CPU oracle correctness did not pass")
    if report.get("zero_orphans") != "passed":
        raise ReadinessError("Metal ownership did not reach zero orphans")
    if report.get("fallback") != "absent":
        raise ReadinessError("Metal execution reported CPU fallback")
    if report.get("unsupported_metrics") != list(UNSUPPORTED_METRICS):
        raise ReadinessError("unsupported telemetry was relabelled")

    for field in SHA_FIELDS:
        _sha256_bytes(report.get(field), field)
    for field in U64_FIELDS:
        _u64(report.get(field), field)

    for field, expected in (
        ("workload_profile_sha256", CANONICAL_WORKLOAD_PROFILE_SHA256),
        ("artifact_sha256", CANONICAL_ARTIFACT_SHA256),
        ("build_sha256", CANONICAL_BUILD_SHA256),
        ("backend_sha256", CANONICAL_BACKEND_SHA256),
        ("challenge_sha256", CANONICAL_CHALLENGE_SHA256),
        ("oracle_output_sha256", CANONICAL_ORACLE_OUTPUT_SHA256),
    ):
        if report[field] != expected:
            raise ReadinessError(f"{field} does not identify the v1 fixture")
    if report["device_info_abi"] != DEVICE_INFO_ABI:
        raise ReadinessError("Metal device ABI changed")
    if (
        report["device_registry_id"] == 0
        or report["dispatch_device_registry_id"]
        != report["device_registry_id"]
        or report["diagnostic_device_registry_id"]
        != report["device_registry_id"]
    ):
        raise ReadinessError("selected Metal device has no identity")
    if any(
        report[field] == 0
        for field in (
            "device_max_threads_x",
            "device_max_threads_y",
            "device_max_threads_z",
        )
    ):
        raise ReadinessError("Metal device thread limits are invalid")
    if any(
        report[field] not in (0, 1)
        for field in (
            "device_low_power",
            "device_headless",
            "device_removable",
            "device_unified_memory",
        )
    ):
        raise ReadinessError("Metal device flags are invalid")
    if report["logical_cpu_count"] < 1:
        raise ReadinessError("logical CPU readiness is invalid")
    if report["queue_count"] != 1:
        raise ReadinessError("readiness plan must use exactly one queue")
    if report["direct_metric_bits"] != DIRECT_METRIC_BITS:
        raise ReadinessError("direct metric set changed")
    if report["unsupported_metric_bits"] != UNSUPPORTED_METRIC_BITS:
        raise ReadinessError("unsupported metric set changed")
    if (
        report["missing_observation_count"] != 2
        or report["unsupported_observation_count"] != 24
        or report["unavailable_reason_count"] != 26
        or report["present_reason_count"] != 0
    ):
        raise ReadinessError("availability/reason accounting changed")
    if report["dispatch_ordinal"] != 1:
        raise ReadinessError("readiness workload did not dispatch exactly once")
    if (
        report["host_submit_ticks"] == 0
        or report["host_complete_ticks"] <= report["host_submit_ticks"]
    ):
        raise ReadinessError("host dispatch bounds are invalid")
    if (
        report["current_allocated_before"] == 0
        or report["current_allocated_after"] == 0
    ):
        raise ReadinessError("Metal allocation samples are invalid")
    if report["command_status"] != COMPLETED_COMMAND_BUFFER_STATUS:
        raise ReadinessError("Metal command buffer did not complete")
    if report["live_weights_after"] != 0:
        raise ReadinessError("Metal weight ownership leaked")
    if report["workload_evidence_abi"] != WORKLOAD_EVIDENCE_ABI:
        raise ReadinessError("Metal workload evidence ABI changed")
    max_abs_error_bits = _u32(
        report["max_abs_error_bits"],
        "max_abs_error_bits",
    )
    maximum_abs_error = _float_from_bits(max_abs_error_bits)
    if (
        max_abs_error_bits & 0x80000000
        or not math.isfinite(maximum_abs_error)
        or maximum_abs_error > MAXIMUM_ABS_ERROR
    ):
        raise ReadinessError("Metal correctness error is invalid")
    if (
        report["live_weights_before"] != 0
        or report["workload_live_weights_after"] != 0
        or report["completed_dispatches_before"] != 0
        or report["completed_dispatches_after"] != 1
        or report["live_weights_after"]
        != report["workload_live_weights_after"]
        or report["dispatch_ordinal"]
        != report["completed_dispatches_after"]
    ):
        raise ReadinessError("Metal workload ownership counters are invalid")
    if (
        report["workload_invocations"] != 1
        or report["profile_count"] != 1
        or report["item_count"] != 1
    ):
        raise ReadinessError("readiness workload cardinality changed")

    start = _double_from_bits(report["gpu_start_time_bits"])
    end = _double_from_bits(report["gpu_end_time_bits"])
    if (
        not math.isfinite(start)
        or not math.isfinite(end)
        or start <= 0
        or end <= start
    ):
        raise ReadinessError("Metal GPU timestamps are invalid")
    duration_float = (end - start) * 1_000_000_000.0
    if (
        not math.isfinite(duration_float)
        or duration_float < 1
        or duration_float > U64_MAX
    ):
        raise ReadinessError("Metal GPU duration is outside u64")
    duration = int(duration_float)
    if report["gpu_duration_nanoseconds"] != duration:
        raise ReadinessError("Metal GPU duration contradicts timestamps")

    expected_device = device_identity_sha256(report)
    if any(
        report[field] != expected_device
        for field in (
            "plan_device_sha256",
            "receipt_device_sha256",
            "diagnostic_device_sha256",
        )
    ):
        raise ReadinessError("Metal device root or alias mismatch")
    expected_placement = placement_identity_sha256(report)
    if any(
        report[field] != expected_placement
        for field in (
            "plan_placement_sha256",
            "receipt_placement_sha256",
            "diagnostic_placement_sha256",
        )
    ):
        raise ReadinessError("Metal placement root or alias mismatch")
    if report["machine_sha256"] != machine_identity_sha256(report):
        raise ReadinessError("machine root does not bind CPU and device")
    if len(
        {
            report["descriptor_sha256"],
            report["plan_descriptor_sha256"],
            report["report_descriptor_sha256"],
            report["diagnostic_descriptor_sha256"],
        }
    ) != 1:
        raise ReadinessError("descriptor root aliases disagree")
    if len(
        {
            report["plan_sha256"],
            report["report_plan_sha256"],
            report["diagnostic_plan_sha256"],
        }
    ) != 1:
        raise ReadinessError("plan root aliases disagree")
    for left, right, label in (
        (
            "probe_bundle_sha256",
            "diagnostic_probe_bundle_sha256",
            "probe bundle",
        ),
        (
            "pre_run_bundle_sha256",
            "diagnostic_pre_run_bundle_sha256",
            "pre-run bundle",
        ),
        (
            "post_run_bundle_sha256",
            "diagnostic_post_run_bundle_sha256",
            "post-run bundle",
        ),
        (
            "run_report_sha256",
            "diagnostic_run_report_sha256",
            "run report",
        ),
    ):
        if report[left] != report[right]:
            raise ReadinessError(f"{label} root aliases disagree")
    if len(
        {
            report["workload_receipt_sha256"],
            report["report_workload_receipt_sha256"],
            report["diagnostic_workload_receipt_sha256"],
        }
    ) != 1:
        raise ReadinessError("workload receipt root aliases disagree")

    expected_dispatch = dispatch_receipt_sha256(report)
    if (
        report["dispatch_receipt_sha256"] != expected_dispatch
        or report["diagnostic_dispatch_receipt_sha256"]
        != expected_dispatch
    ):
        raise ReadinessError("dispatch receipt root or alias mismatch")
    if report["correctness_sha256"] != correctness_sha256(report):
        raise ReadinessError("correctness root mismatch")
    if report["ownership_sha256"] != ownership_sha256(report):
        raise ReadinessError("ownership root mismatch")
    expected_report = diagnostic_report_sha256(report)
    if report["report_sha256"] != expected_report:
        raise ReadinessError("diagnostic report root mismatch")


def _terminate_runner(process: subprocess.Popen[bytes]) -> None:
    if os.name == "posix":
        try:
            os.killpg(process.pid, signal.SIGTERM)
            return
        except (ProcessLookupError, PermissionError):
            pass
    if process.poll() is not None:
        return
    try:
        process.terminate()
    except ProcessLookupError:
        pass


def _kill_runner(process: subprocess.Popen[bytes]) -> None:
    if os.name == "posix":
        try:
            os.killpg(process.pid, signal.SIGKILL)
            return
        except (ProcessLookupError, PermissionError):
            pass
    if process.poll() is not None:
        return
    try:
        process.kill()
    except ProcessLookupError:
        pass


def _bounded_runner_output(
    command: Sequence[str],
    timeout_seconds: float,
) -> Tuple[int, bytes, bytes]:
    """Capture both pipes while keeping each allocation at max + one byte."""
    try:
        valid_timeout = (
            not isinstance(timeout_seconds, bool)
            and math.isfinite(timeout_seconds)
            and timeout_seconds > 0
        )
    except (OverflowError, TypeError):
        valid_timeout = False
    if not valid_timeout:
        raise ReadinessError("runner timeout must be positive")
    try:
        process = subprocess.Popen(
            list(command),
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env={"LC_ALL": "C", "PATH": os.defpath},
            close_fds=True,
            start_new_session=os.name == "posix",
        )
    except (OSError, TypeError, ValueError) as exc:
        raise ReadinessError(f"could not start readiness runner: {exc}") from exc
    if process.stdout is None or process.stderr is None:
        _kill_runner(process)
        raise ReadinessError("could not capture readiness runner output")

    stdout = bytearray()
    stderr = bytearray()
    failure: List[Tuple[str, str]] = []
    failure_lock = threading.Lock()
    wake = threading.Event()
    readers_done = [threading.Event(), threading.Event()]

    def fail(kind: str, detail: str) -> None:
        with failure_lock:
            if not failure:
                failure.append((kind, detail))
                _terminate_runner(process)
        wake.set()

    def drain(
        stream: Any,
        destination: bytearray,
        name: str,
        done: threading.Event,
    ) -> None:
        try:
            while True:
                remaining = MAX_RUNNER_OUTPUT_BYTES + 1 - len(destination)
                if remaining <= 0:
                    fail("bound", name)
                    return
                chunk = stream.read(min(64 * 1024, remaining))
                if not chunk:
                    return
                destination.extend(chunk)
                if len(destination) > MAX_RUNNER_OUTPUT_BYTES:
                    fail("bound", name)
                    return
        except (OSError, ValueError) as exc:
            fail("capture", f"{name}: {exc}")
        finally:
            done.set()
            wake.set()

    threads = [
        threading.Thread(
            target=drain,
            args=(process.stdout, stdout, "stdout", readers_done[0]),
            daemon=True,
        ),
        threading.Thread(
            target=drain,
            args=(process.stderr, stderr, "stderr", readers_done[1]),
            daemon=True,
        ),
    ]
    for thread in threads:
        thread.start()

    deadline = time.monotonic() + timeout_seconds
    timed_out = False
    while True:
        if failure:
            break
        if (
            process.poll() is not None
            and readers_done[0].is_set()
            and readers_done[1].is_set()
        ):
            break
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            timed_out = True
            _terminate_runner(process)
            break
        wake.wait(min(remaining, 0.01))
        wake.clear()

    if timed_out or failure:
        _terminate_runner(process)
        try:
            process.wait(timeout=RUNNER_TERMINATE_GRACE_SECONDS)
        except subprocess.TimeoutExpired:
            _kill_runner(process)
            try:
                process.wait(timeout=RUNNER_TERMINATE_GRACE_SECONDS)
            except subprocess.TimeoutExpired as exc:
                raise ReadinessError(
                    "native readiness runner could not be killed"
                ) from exc
        if os.name == "posix":
            # The session leader may have exited while a descendant ignored
            # SIGTERM and retained a pipe. Kill the isolated group as well.
            _kill_runner(process)
        for stream in (process.stdout, process.stderr):
            try:
                stream.close()
            except OSError:
                pass

    for thread in threads:
        thread.join(timeout=RUNNER_TERMINATE_GRACE_SECONDS)
    if any(thread.is_alive() for thread in threads):
        for stream in (process.stdout, process.stderr):
            try:
                stream.close()
            except OSError:
                pass
        for thread in threads:
            thread.join(timeout=RUNNER_TERMINATE_GRACE_SECONDS)
    if any(thread.is_alive() for thread in threads):
        raise ReadinessError("native readiness runner pipes did not close")
    for stream in (process.stdout, process.stderr):
        try:
            stream.close()
        except OSError:
            pass
    if timed_out:
        raise ReadinessError(
            f"native readiness runner exceeded {timeout_seconds:g}s timeout"
        )
    if failure:
        kind, detail = failure[0]
        if kind == "bound":
            raise ReadinessError(
                f"native readiness runner {detail} exceeded "
                f"{MAX_RUNNER_OUTPUT_BYTES} byte bound"
            )
        raise ReadinessError(
            f"native readiness runner output capture failed: {detail}"
        )
    return process.returncode, bytes(stdout), bytes(stderr)


def _reject_duplicate_keys(pairs: List[Tuple[str, Any]]) -> Dict[str, Any]:
    result: Dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ReadinessError(f"duplicate JSON field: {key}")
        result[key] = value
    return result


def _reject_json_constant(value: str) -> Any:
    raise ReadinessError(f"invalid JSON numeric constant: {value}")


def _parse_json_integer(value: str) -> int:
    digits = value[1:] if value.startswith("-") else value
    if len(digits) > MAX_JSON_INTEGER_DIGITS:
        raise ReadinessError("JSON integer exceeds u64 digit bound")
    return int(value, 10)


def _parse_report(stdout: bytes) -> Dict[str, Any]:
    lines = stdout.splitlines()
    if len(lines) != 1 or not lines[0]:
        raise ReadinessError("native readiness runner must emit one JSON line")
    try:
        text = lines[0].decode("utf-8", errors="strict")
        parsed = json.loads(
            text,
            object_pairs_hook=_reject_duplicate_keys,
            parse_constant=_reject_json_constant,
            parse_int=_parse_json_integer,
        )
    except (
        UnicodeDecodeError,
        json.JSONDecodeError,
        ValueError,
        RecursionError,
    ) as exc:
        raise ReadinessError(
            "native readiness runner emitted invalid JSON"
        ) from exc
    if not isinstance(parsed, dict):
        raise ReadinessError("native readiness report must be an object")
    return parsed


def run_runner(
    command: Sequence[str],
    timeout_seconds: float = RUNNER_TIMEOUT_SECONDS,
) -> Dict[str, Any]:
    if not command:
        raise ReadinessError("missing readiness runner command")
    returncode, stdout, stderr = _bounded_runner_output(
        command,
        timeout_seconds,
    )
    if returncode != 0:
        detail = stderr[:4096].decode("utf-8", errors="replace")
        raise ReadinessError(
            f"native readiness runner failed ({returncode}): {detail}"
        )
    parsed = _parse_report(stdout)
    validate_report(parsed)
    return parsed


def make_test_report() -> Dict[str, Any]:
    start = 1234.0
    end = 1234.000002
    report: Dict[str, Any] = {
        "schema": SCHEMA,
        "claim_class": "diagnostic",
        "performance_claim": False,
        "decision": "publishable",
        "workload_status": "succeeded",
        "correctness": "passed",
        "zero_orphans": "passed",
        "fallback": "absent",
        "device_info_abi": DEVICE_INFO_ABI,
        "device_registry_id": 17,
        "dispatch_device_registry_id": 17,
        "diagnostic_device_registry_id": 17,
        "recommended_max_working_set_size": 1 << 30,
        "device_location": 1,
        "device_location_number": 0,
        "device_max_threads_x": 1024,
        "device_max_threads_y": 1024,
        "device_max_threads_z": 64,
        "device_low_power": 1,
        "device_headless": 0,
        "device_removable": 0,
        "device_unified_memory": 1,
        "logical_cpu_count": 8,
        "queue_count": 1,
        "direct_metric_bits": DIRECT_METRIC_BITS,
        "unsupported_metric_bits": UNSUPPORTED_METRIC_BITS,
        "missing_observation_count": 2,
        "unsupported_observation_count": 24,
        "unavailable_reason_count": 26,
        "present_reason_count": 0,
        "dispatch_ordinal": 1,
        "host_submit_ticks": 100,
        "host_complete_ticks": 200,
        "current_allocated_before": 4096,
        "current_allocated_after": 4096,
        "gpu_start_time_bits": struct.unpack("<Q", struct.pack("<d", start))[0],
        "gpu_end_time_bits": struct.unpack("<Q", struct.pack("<d", end))[0],
        "gpu_duration_nanoseconds": int((end - start) * 1_000_000_000.0),
        "command_status": COMPLETED_COMMAND_BUFFER_STATUS,
        "live_weights_after": 0,
        "workload_evidence_abi": WORKLOAD_EVIDENCE_ABI,
        "max_abs_error_bits": struct.unpack(
            "<I", struct.pack("<f", 0.000001)
        )[0],
        "live_weights_before": 0,
        "workload_live_weights_after": 0,
        "completed_dispatches_before": 0,
        "completed_dispatches_after": 1,
        "workload_invocations": 1,
        "profile_count": 1,
        "item_count": 1,
        "unsupported_metrics": list(UNSUPPORTED_METRICS),
    }
    for field in SHA_FIELDS:
        report[field] = hashlib.sha256(field.encode("ascii")).hexdigest()
    for field, value in (
        ("workload_profile_sha256", CANONICAL_WORKLOAD_PROFILE_SHA256),
        ("artifact_sha256", CANONICAL_ARTIFACT_SHA256),
        ("build_sha256", CANONICAL_BUILD_SHA256),
        ("backend_sha256", CANONICAL_BACKEND_SHA256),
        ("challenge_sha256", CANONICAL_CHALLENGE_SHA256),
        ("oracle_output_sha256", CANONICAL_ORACLE_OUTPUT_SHA256),
    ):
        report[field] = value
    report["plan_descriptor_sha256"] = report["descriptor_sha256"]
    report["report_descriptor_sha256"] = report["descriptor_sha256"]
    report["diagnostic_descriptor_sha256"] = report["descriptor_sha256"]
    report["report_plan_sha256"] = report["plan_sha256"]
    report["diagnostic_plan_sha256"] = report["plan_sha256"]
    device_sha256 = device_identity_sha256(report)
    for field in (
        "plan_device_sha256",
        "receipt_device_sha256",
        "diagnostic_device_sha256",
    ):
        report[field] = device_sha256
    report["machine_sha256"] = machine_identity_sha256(report)
    placement_sha256 = placement_identity_sha256(report)
    for field in (
        "plan_placement_sha256",
        "receipt_placement_sha256",
        "diagnostic_placement_sha256",
    ):
        report[field] = placement_sha256
    for primary, aliases in (
        ("probe_bundle_sha256", ("diagnostic_probe_bundle_sha256",)),
        ("pre_run_bundle_sha256", ("diagnostic_pre_run_bundle_sha256",)),
        ("post_run_bundle_sha256", ("diagnostic_post_run_bundle_sha256",)),
        (
            "workload_receipt_sha256",
            (
                "report_workload_receipt_sha256",
                "diagnostic_workload_receipt_sha256",
            ),
        ),
        ("run_report_sha256", ("diagnostic_run_report_sha256",)),
    ):
        for alias in aliases:
            report[alias] = report[primary]
    report["dispatch_receipt_sha256"] = dispatch_receipt_sha256(report)
    report["diagnostic_dispatch_receipt_sha256"] = report[
        "dispatch_receipt_sha256"
    ]
    report["correctness_sha256"] = correctness_sha256(report)
    report["ownership_sha256"] = ownership_sha256(report)
    report["report_sha256"] = diagnostic_report_sha256(report)
    return report


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Verify native macOS Metal readiness evidence"
    )
    parser.add_argument("--runner", nargs="+", required=True)
    args = parser.parse_args(argv)
    try:
        report = run_runner(args.runner)
    except (OSError, subprocess.SubprocessError, ReadinessError) as exc:
        print(f"native-metal-readiness: {exc}", file=sys.stderr)
        return 1
    print(f"native-metal-readiness: ok {report['report_sha256']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
